apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  # root password for MySQL
  # the actual password is varMyRootPass
  # echo -n varMyRootPass | base64
rootpw: Wavelabs#123
