spec:
  template:
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: jdbc:mysql://testdb.c7rcwy3juna9.ap-south-1.rds.amazonaws.com
            valueFrom:
              # rather than embed sensitive details in this config
              # we reference another Kubernetes object
              # in this case, the Secret with the name: mysql-credentials
              secretKeyRef:
                name: mysql-credentials
                # references the rootpw key-value pair from the mysql-credentials Secret
                key: rootpw
          
