apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: mysql
  name: mysql
spec: 
  ports: 
    - port: 3306
      protocol: TCP
      targetPort: 3306
kind: Endpoints
metadata:
  name: mysql
subsets:
- addresses:
  - ip: testdb.c7rcwy3juna9.ap-south-1.rds.amazonaws.com
  ports:
  - port: 3306
    name: mysql
    protocol: TCP
